#define _DEFAULT_SOURCE

#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <net/if.h>
#include <netinet/ether.h>
#include <netinet/if_ether.h>
#include <netinet/ip.h>
#include <netinet/ip_icmp.h>
#include <netpacket/packet.h>
#include <poll.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#define logf(...) fprintf(stderr, __VA_ARGS__)

#define MAX_PACKET_BUF 16384
#define BUF_POOL_SIZE 6
#define SLIP_SEND_QUEUE_SIZE 2
#define ETH_SEND_QUEUE_SIZE 2

#define SER_IDX 0
#define ETH_IDX 1
#define FDS_SIZE 2

struct dhcp_msg {
  uint8_t op;
  uint8_t htype;
  uint8_t hlen;
  uint8_t hops;
  uint32_t xid;
  uint16_t secs;
  uint16_t flags;
  uint32_t ciaddr;
  uint32_t yiaddr;
  uint32_t siaddr;
  uint32_t giaddr;
  uint8_t chaddr[16];
  uint8_t sname[64];
  uint8_t file[128];
  uint8_t options[312];
} __attribute__((packed));

struct arp_msg {
  uint16_t hrd;  // 1 or 6?
  uint16_t pro;  // ETH_P_IP
  uint8_t hln;   // 6 -- MAC len
  uint8_t pln;   // 4 -- IPv4 address len
  uint16_t op;   // 1=ARP req, rep, 3=RARP req, rep, 5=DRARP req, rep, err,
                 // 8=InARP req, rep
  uint8_t addrs[255 * 4];
  // sha, spa, tha, tpa
};

struct packet {
  union {
    struct {
      struct ethhdr eth;
      struct iphdr ip;
      union {
        struct dhcp_msg dhcp;
        struct arp_msg arp;
      };
    };
    uint8_t raw[MAX_PACKET_BUF];
  };
};

// Adapted from sample code in RFC 1055

// SLIP special character codes
#define SLIP_END 0300     /* indicates end of packet */
#define SLIP_ESC 0333     /* indicates byte stuffing */
#define SLIP_ESC_END 0334 /* ESC ESC_END means END data byte */
#define SLIP_ESC_ESC 0335 /* ESC ESC_ESC means ESC data byte */

void send_char(uint8_t c) {}
uint8_t recv_char(void) { return SLIP_END; }

// slip_send_packet: sends a packet of length "len", starting at location "p".
void slip_send_packet(uint8_t *p, size_t len) {
  // Send an initial END character to flush out any data that may have
  // accumulated in the receiver due to line noise
  send_char(SLIP_END);

  // For each byte in the packet, send the appropriate character sequence
  while (len--) {
    switch (*p) {
      // If it's the same code as an END character, we send a special two
      // character code so as not to make the receiver think we sent an END
      case SLIP_END:
        send_char(SLIP_ESC);
        send_char(SLIP_ESC_END);
        break;

#ifndef TIGHTER_SLIP
      // If it's the same code as an ESC character, we send a special two
      // character code so as not to make the receiver think we sent an ESC
      case SLIP_ESC:
        send_char(SLIP_ESC);
        send_char(SLIP_ESC_ESC);
        break;
#else
      case SLIP_ESC:
        // If it's the same code as an ESC character, we send a special two
        // character code so as not to make the receiver think we sent an ESC
        if (!len || (p[1] == SLIP_ESC_END) || (p[1] == SLIP_ESC_ESC)) {
          send_char(SLIP_ESC);
          send_char(SLIP_ESC_ESC);
        } else {
          len--;
          p++;
          send_char(SLIP_ESC);
          send_char(*p);
        }
        break;
#endif
      // Otherwise, we just send the character
      default:
        send_char(*p);
    }

    p++;
  }

  /* tell the receiver that we're done sending the packet
   */
  send_char(SLIP_END);
}

// slip_recv_packet: receives a packet into the buffer located at "p".
// If more than len bytes are received, the packet will be truncated. Returns
// the number of bytes stored in the buffer.
size_t slip_recv_packet(uint8_t *p, size_t len) {
  char c;
  size_t received = 0;

  // Sit in a loop reading bytes until we put together a whole packet. Make sure
  // not to copy them into the packet if we run out of room.
  for (;;) {
    // Get a character to process
    c = recv_char();

    // Handle bytestuffing if necessary
    switch (c) {
      // If it's an END character then we're done with the packet
      case SLIP_END:
        // A minor optimization: if there is no data in the packet, ignore it.
        // This is meant to avoid bothering IP with all the empty packets
        // generated by the duplicate END characters which are in turn sent to
        // try to detect line noise.
        if (received) {
          return received;
        } else {
          break;
        }

#ifndef TIGHTER_SLIP
      // If it's the same code as an ESC character, wait and get another
      // character and then figure out what to store in the packet based on
      // that.
      case SLIP_ESC:
        c = recv_char();

        // If "c" is not one of these two, then we have a protocol violation.
        // The best bet seems to be to leave the byte alone and just stuff it
        // into the packet.
        switch (c) {
          case SLIP_ESC_END:
            if (received < len) p[received++] = c;
            c = SLIP_END;
            break;
          case SLIP_ESC_ESC:
            c = SLIP_ESC;
            break;
          default:
            // Don't change c!
            break;
        }
#else
      // If it's the same code as an ESC character, wait and get another
      // character and then figure out what to store in the packet based on
      // that.
      case SLIP_ESC:
        c = recv_char();

        // If "c" is not one of these two, then we have a protocol violation.
        // The best bet seems to be to leave the byte alone and just stuff it
        // into the packet.

        // JL: I have a better idea, let's stuff the ESC *and* the following
        // char, and that way the client can save escaping the escape around
        // half the time. This decode is compatible with the reference encoder,
        // and improves stuffing of random packets from ~1% expansion to ~0.5%.

        // What this ends up looking like is:
        // ESC ESC_ESC -> ESC
        // ESC ESC_END -> END
        // ESC_ESC -> ESC_ESC
        // ESC_END -> ESC_END
        // ESC ESC -> ESC ESC
        // ESC x -> ESC x (where x != ESC_END, x != ESC_ESC)
        // END -> ends packet

        // From the encoding side, in the most efficient coding:
        // END -> ESC ESC_ESC
        // ESC ESC_END -> ESC ESC_ESC ESC_END
        // ESC x -> ESC x (where x != END)
        // everything else is passed through literally.

        switch (c) {
          case SLIP_ESC_END:
            if (received < len) p[received++] = c;
            c = SLIP_END;
            break;
          case SLIP_ESC_ESC:
            c = SLIP_ESC;
            break;
          default:
            if (received < len) p[received++] = SLIP_ESC;
            // Don't change c!
            break;
        }
#endif
      // Here we fall into the default handler and let it store the character
      // for us
      default:
        if (received < len) {
          p[received++] = c;
        }
        break;
    }
  }
}

uint8_t ser_slip_buf[MAX_PACKET_BUF * 2 + 16];
struct packet ser_send_queue[SLIP_SEND_QUEUE_SIZE];
struct packet eth_send_queue[ETH_SEND_QUEUE_SIZE];
size_t ser_send_head = 0;
size_t ser_send_tail = 0;
size_t eth_send_head = 0;
size_t eth_send_tail = 0;

size_t ser_recv_so_far = 0;

int ser_fd;
int eth_socket;

// the MAC address we're applying to packets bridged from the SLIP interface
struct ether_addr eth_mac;
struct ether_addr broadcast_mac = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};

// the MAC address the SLIP device uses for itself (only in DHCP packets)
struct ether_addr ser_dhcp_mac;

void parse_args(int argc, char *argv[]);

void print_usage_and_exit(char const *argv0, char const *extra_message,
                          int result);

void poll_loop(void);

void ser_read_available(void);

void ser_accumulate_bytes(uint8_t *data, size_t size);
void ser_process(void *frame);
bool ser_process_dhcp_request(void *frame);

void eth_read_available(void);

bool eth_process_dhcp_response(void *eth_frame);
bool eth_process_arp_request(void *eth_frame);

int eth_get_ifindex(int eth_socket, char const *dev_name);
void eth_get_hwaddr(int eth_socket, char const *dev_name,
                    struct ether_addr *hwaddr);

uint16_t ip_header_checksum(void const *frame, size_t header_size);
bool validate_ip_frame(void const *eth_frame, size_t eth_size);
void *get_ip_frame(void *eth_frame);
size_t get_ip_frame_size(void *frame);
uint8_t *get_ip_payload(void *eth_frame, size_t *out_payload_size);

int main(int argc, char *argv[]) {
  parse_args(argc, argv);

  poll_loop();

  return 0;
}

void parse_args(int argc, char *argv[]) {
  char ser_dev_name[PATH_MAX] = "";
  char eth_dev_name[IFNAMSIZ] = "";
  struct ether_addr const *tmp_mac;

  bool force_eth_mac = false;

  int opt;
  int res;
  while ((opt = getopt(argc, argv, "s:e:m:Mh")) != -1) {
    switch (opt) {
      case 'm':
        force_eth_mac = true;
        if ((tmp_mac = ether_aton(optarg)) == NULL) {
          print_usage_and_exit(argv[0], "Bad arg: expected MAC address", 1);
        }
        memcpy(&eth_mac, tmp_mac, sizeof(struct ether_addr));
        break;
      case 's':
        snprintf(ser_dev_name, PATH_MAX, "%s", optarg);
        break;
      case 'e':
        snprintf(eth_dev_name, IFNAMSIZ, "%s", optarg);
        break;
      case 'h':
        print_usage_and_exit(argv[0], NULL, 0);
        break;
      default:
        print_usage_and_exit(argv[0], "Invalid option", 1);
        break;
    }
  }

  // TODO enumerate serial devices
  // if (strlen(rx_dev_name) == 0) {
  //   snprintf(rx_dev_name, sizeof rx_dev_name, "wlp3s0");
  // }

  // TODO enumerate ethernet devices
  // if (strlen(tx_dev_name) == 0) {
  //   snprintf(tx_dev_name, sizeof tx_dev_name, "enp0s25");
  // }

  ser_fd = open(ser_dev_name, O_RDWR | O_NOCTTY);
  if (ser_fd < 0) {
    perror("open() failed for serial socket");
    exit(1);
  }

  // Create a raw socket
  eth_socket = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL));
  if (eth_socket < 0) {
    perror("socket() failed for ethernet socket");
    exit(1);
  }

  if (!force_eth_mac && strlen(eth_dev_name) > 0) {
    eth_get_hwaddr(eth_socket, eth_dev_name, &eth_mac);
  }
}

void print_usage_and_exit(char const *argv0, char const *extra_message,
                          int result) {
  if (extra_message != NULL) {
    logf("%s\n\n", extra_message);
  }
  logf("Usage: %s [-s SERIALDEV] [-e ETHDEV] [-m MAC | -M]\n", argv0);
  exit(result);
}

void poll_loop(void) {
  struct pollfd poll_fds[FDS_SIZE];

  struct timespec last_keepalive_time;
  clock_gettime(CLOCK_MONOTONIC, &last_keepalive_time);

  for (;;) {
    poll_fds[SER_IDX].fd = ser_fd;
    poll_fds[SER_IDX].events = POLLIN;
    poll_fds[SER_IDX].revents = 0;

    poll_fds[ETH_IDX].fd = eth_socket;
    poll_fds[ETH_IDX].events = POLLIN;
    poll_fds[ETH_IDX].revents = 0;

    int poll_res = poll(poll_fds, 1, 100);

    if (poll_res < 0) {
      perror("poll failed");
      exit(1);
    } else {
      if (poll_res == 0) {
        // Nothing ready yet, check again
        continue;
      }
    }

#if 1
    struct timespec cur_time;
    clock_gettime(CLOCK_MONOTONIC, &cur_time);
    int64_t dmsec =
        ((cur_time.tv_sec - last_keepalive_time.tv_sec) * 1000000000LL +
         (cur_time.tv_nsec - last_keepalive_time.tv_nsec)) /
        1000000LL;

    if (dmsec > 2000) {
      last_keepalive_time = cur_time;
    }
#endif

    // Data available somewhere!
    if ((poll_fds[SER_IDX].revents & ~POLLIN) != 0) {
      int re = poll_fds[SER_IDX].revents;
      logf("While polling ethernet interface: %d ( %s%s%s)", re,
           (re & POLLERR) != 0 ? "ERR " : "", (re & POLLHUP) != 0 ? "HUP " : "",
           (re & POLLNVAL) != 0 ? "INVAL " : "");
    }

    if ((poll_fds[ETH_IDX].revents & ~POLLIN) != 0) {
      int re = poll_fds[ETH_IDX].revents;
      logf("While polling serial interface: %d ( %s%s%s)", re,
           (re & POLLERR) != 0 ? "ERR " : "", (re & POLLHUP) != 0 ? "HUP " : "",
           (re & POLLNVAL) != 0 ? "INVAL " : "");
    }

    if ((poll_fds[SER_IDX].revents & POLLIN) != 0) {
      ser_read_available();
    }
    if ((poll_fds[ETH_IDX].revents & POLLIN) != 0) {
      eth_read_available();
    }
  }
}

void ser_read_available(void) {
  // TODO implement
}

void ser_accumulate_bytes(uint8_t *data, size_t size) {
  // TODO implement
}

void ser_process(void *frame) {
  // TODO implement
}

bool ser_process_dhcp_request(void *frame) {
  // TODO implement
  // first, check if an eth frame is available for the response
}

void eth_read_available(void) {
  // Try reading the ethernet interface -- despite the name it's okay to stop
  // at reading/processing a single packet
  uint8_t *packet_buf = ser_send_queue[ser_send_tail].raw;
  struct sockaddr_storage packet_addr;
  socklen_t packet_addr_len = sizeof packet_addr;
  ssize_t recv_size;

  recv_size = recvfrom(eth_socket, packet_buf, MAX_PACKET_BUF, MSG_DONTWAIT,
                       (struct sockaddr *)&packet_addr, &packet_addr_len);
  if (recv_size < 0) {
    if ((errno == EAGAIN) || (errno == EWOULDBLOCK)) {
      // No message waiting after all
    } else {
      perror("recvfrom failed");
      exit(1);
    }
  } else if ((memcmp(((struct ethhdr const *)packet_buf)->h_dest, &eth_mac,
                     ETH_ALEN) != 0) &&
             (memcmp(((struct ethhdr const *)packet_buf)->h_dest,
                     &broadcast_mac, ETH_ALEN) != 0)) {
    // Ignore, wrong dest
  } else if ((recv_size > MAX_PACKET_BUF) ||
             (packet_addr_len > sizeof packet_addr)) {
    // Ignore packet,it too big
    logf("packet too big: %lu/%lu\n", (unsigned long)recv_size,
         (unsigned long)(sizeof packet_addr));  // packet_addr_len);
  } else if (validate_ip_frame(packet_buf, (size_t)recv_size)) {
    // A complete packet!
    void *ip_frame = get_ip_frame(packet_buf);
    if (ip_frame == NULL) {
      logf("  packet badly formed (%lu bytes):\n", (unsigned long)recv_size);
      // hex_dump(packet_buf, recv_size > 64 ? 64 : (size_t)recv_size);
      if (recv_size > 64) {
        logf("  ...\n");
      }
    } else {
      size_t ip_frame_size = get_ip_frame_size(ip_frame);
      if (ip_frame_size > recv_size) {
        logf("  bad frame size!\n");
      } else {
        if (ip_frame_size + sizeof(struct ethhdr) < recv_size) {
          logf("  runt IP frame!\n");
        }
        // hex_dump(ip_frame, ip_frame_size > 64 ? 64 : (size_t)ip_frame_size);
        if (ip_frame_size > 64) {
          logf("  ...\n");
        }
      }
    }
  }
}

bool eth_process_dhcp_response(void *eth_frame) {
  // TODO implement
  // first, check if a ser frame is available for the response
}

bool eth_process_arp_request(void *eth_frame) {
  // TODO implement
#if 0
  struct icmpechopkt ping_pkt;

  memset(&ping_pkt, 0, sizeof ping_pkt);

  memcpy(&ping_pkt.eth.h_source, &source_mac.ether_addr_octet, ETH_ALEN);
  memcpy(&ping_pkt.eth.h_dest, &dest_mac.ether_addr_octet, ETH_ALEN);
  ping_pkt.eth.h_proto = htons(ETH_P_IP);

  ping_pkt.ip.version = 4;
  ping_pkt.ip.ihl = 5;
  ping_pkt.ip.tos = 0;
  ping_pkt.ip.tot_len = htons(offsetof(struct ping_pkt_struct, payload[32]) -
                              offsetof(struct ping_pkt_struct, ip));
  ping_pkt.ip.id = htons(0x3103);
  ping_pkt.ip.frag_off = htons(0);
  ping_pkt.ip.ttl = 0x80;
  ping_pkt.ip.protocol = 0x01;
  // ping_pkt.ip.check
  // ping_pkt.ip.saddr = htonl(0xC0A80078);
  // ping_pkt.ip.daddr = htonl(0xC0A800DC);
  ping_pkt.ip.saddr = source_ip.s_addr;
  ping_pkt.ip.daddr = dest_ip.s_addr;
  ping_pkt.ip.check = ip_header_checksum(&ping_pkt.ip, sizeof(struct iphdr));

  ping_pkt.icmp.type = 0x08;
  ping_pkt.icmp.code = 0x00;
  // ping_pkt.ping.checksum
  struct timespec cur_time;
  clock_gettime(CLOCK_MONOTONIC, &cur_time);
  ping_pkt.icmp.un.echo.id =
      htons(((cur_time.tv_nsec / 1000) ^ cur_time.tv_sec) & 0xFFFF);
  ping_pkt.icmp.un.echo.sequence = htons(1);
  strncpy(ping_pkt.payload, "abcdefghijklmnopqrstuvwabcdefghi", 32);
  ping_pkt.icmp.checksum = ip_header_checksum(
      &ping_pkt.icmp, offsetof(struct ping_pkt_struct, payload[32]) -
                          offsetof(struct ping_pkt_struct, icmp));
#endif
}

int eth_get_ifindex(int eth_socket, char const *dev_name) {
  struct ifreq if_ioreq;

  memset(&if_ioreq, 0, sizeof if_ioreq);
  snprintf(if_ioreq.ifr_name, IFNAMSIZ, "%s", dev_name);
  if (ioctl(eth_socket, SIOCGIFINDEX, &if_ioreq) < 0) {
    perror("get socket index failed");
    exit(1);
  }
  return if_ioreq.ifr_ifindex;
}

void eth_get_hwaddr(int eth_socket, char const *dev_name,
                    struct ether_addr *hwaddr) {
  struct ifreq if_ioreq;

  memset(&if_ioreq, 0, sizeof if_ioreq);
  snprintf(if_ioreq.ifr_name, IFNAMSIZ, "%s", dev_name);
  if (ioctl(eth_socket, SIOCGIFHWADDR, &if_ioreq) < 0) {
    perror("get socket hardware address failed");
    exit(1);
  }
  memcpy(hwaddr, if_ioreq.ifr_hwaddr.sa_data, ETH_ALEN);
}

uint16_t ip_header_checksum(void const *frame, size_t header_size) {
  uint8_t const *const buf = (uint8_t const *)frame;
  uint32_t checksum = 0;

  for (size_t i = 0; i < header_size / 2; ++i) {
    checksum += ((uint16_t const *)buf)[i];
  }

  checksum = ((checksum >> 16) + (checksum & 0xFFFF));
  checksum = ((checksum >> 16) + (checksum & 0xFFFF));
  return ~checksum & 0xFFFF;
}

bool validate_ip_frame(void const *eth_frame, size_t eth_size) {
  uint8_t const *buf = (uint8_t const *)eth_frame;
  struct ethhdr const *eth_header = (struct ethhdr const *)eth_frame;

  logf("dest: ");
  for (size_t i = 0; i < ETH_ALEN; ++i) {
    if (i > 0) logf(":");
    logf("%02X", (int)eth_header->h_dest[i]);
  }

  logf(", src: ");
  for (size_t i = 0; i < ETH_ALEN; ++i) {
    if (i > 0) logf(":");
    logf("%02X", (int)eth_header->h_source[i]);
  }

  uint16_t proto = ntohs(eth_header->h_proto);
  size_t size = 0;
  logf(", proto: 0x%X, eth_size:%lu\n", (unsigned)proto,
       (unsigned long)eth_size);

  if (proto < ETH_P_802_3_MIN) {
    size = 0;
    proto = ETH_P_802_3;
  } else if ((proto == ETH_P_IP) &&
             (eth_size >= sizeof(struct ethhdr) + sizeof(struct iphdr))) {
    // The order of these tests is important -- some of them depend on prior
    // tests passing to be safe, e.g. checking the header checksum after
    // verifying that the received packet isn't truncated
    struct iphdr const *header =
        (struct iphdr const *)(buf + sizeof(struct ethhdr));
    if (header->version != 4) {
      logf("  bad version\n");
      return false;
    }
    size_t header_size = header->ihl * 4;
    if (header_size < sizeof(struct iphdr)) {
      logf("  bad header size\n");
      return false;
    }
    if (eth_size < sizeof(struct ethhdr) + header_size) {
      logf("  truncated header\n");
      return false;
    }
    uint16_t checksum = ip_header_checksum(header, header_size);
    if (checksum != 0) {
      logf("  bad header checksum\n");
      return false;
    }
    size = ntohs(header->tot_len);
    if (eth_size < sizeof(struct ethhdr) + size) {
      logf("  truncated packet\n");
      return false;
    }
    logf("  ip_size: %lu\n", (unsigned long)size);
  } else {
    // nothing
  }

  return size > 0;
}

void *get_ip_frame(void *eth_frame) {
  uint8_t *buf = (uint8_t *)eth_frame;
  return buf + sizeof(struct ethhdr);
}

size_t get_ip_frame_size(void *frame) {
  uint8_t *buf = (uint8_t *)frame;
  struct iphdr const *header = (struct iphdr const *)buf;
  return ntohs(header->tot_len);
}

uint8_t *get_ip_payload(void *eth_frame, size_t *out_payload_size) {
  struct iphdr *header = (struct iphdr *)get_ip_frame(eth_frame);
  size_t header_size = header->ihl * 4;
  if (out_payload_size != NULL) {
    *out_payload_size = ntohs(header->tot_len) - header_size;
  }
  return (uint8_t *)header + header_size;
}
